list: $/det/events/models/event/columns.yaml
modelClass: Det\Events\Models\Event
title: Events
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'det/events/events/update/:id'
